[build]
builder = "dockerfile"
[deploy]
restartPolicyType = "ON_FAILURE"
startCommand = "python manage.py makemigrations && python manage.py migrate --run-syncdb && gunicorn PPMA.wsgi:application --bind 0.0.0.0:8080"
