[build]
builder = "dockerfile"
[deploy]
restartPolicyType = "ON_FAILURE"
startCommand = "echo 'Testing DB connection...' && python manage.py check --database default && python manage.py makemigrations WebApp && python manage.py migrate --verbosity=2 && gunicorn PPMA.wsgi:application --bind 0.0.0.0:8080"
