[build]
builder = "dockerfile"
[deploy]
restartPolicyType = "ON_FAILURE"
startCommand = "python manage.py makemigrations --empty WebApp && python manage.py makemigrations WebApp && python manage.py showmigrations && python manage.py migrate --fake-initial && python manage.py migrate && gunicorn PPMA.wsgi:application --bind 0.0.0.0:8080"
